### ISSUE TITLE
Value functions

### ISSUE THREAD

**Issue by jklmnn** [Componolit/basalt#7]
Similar to the `Image` functions the `Strings` and `Strings_Generic` package should provide `Value` functions that allow parsing a value from a string for the most common types.

The exact behaviour needs to be defined (especially how to deal with Strings that do not describe a value in range and which notations should be accepts for each type).

**Comment by senier** [comment]
Idea: Make a value function that returns an option type (variant record) which encodes the result of the operation. Error type could be "too long", "invalid format", ... We would like to parse Ada style literals (`16#deadbeef#`), C style hex numbers (`0xdeadbeef`) and raw numbers with an explicit base.

**Comment by jklmnn** [comment]
Fixed by #17.
